"""upgraded auth

Revision ID: 211c232b91b9
Revises: 
Create Date: 2025-01-18 22:31:21.189116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211c232b91b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_fridge', schema=None) as batch_op:
        batch_op.alter_column('purchase_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('expiry_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_fridge', schema=None) as batch_op:
        batch_op.alter_column('expiry_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('purchase_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
